#!/bin/bash
# --------------------------------------------------------------------------------------------------------
# Name : Account Administrator Access Group Policies
#
# Description: Set the policies in an Access Group to allow administration of an Account
# so Developer Tools environments can be installed.
#
# --------------------------------------------------------------------------------------------------------
#
# input validation
if [ -z "$1" ]; then
    echo "Usage: acp-acct <ACCESS_GROUP>"
    echo "Create an Access Group with the Access Policies for an account administrator"
    exit
fi

ACCESS_GROUP=$1

# input validation
if [ -z "${ACCESS_GROUP}" ]; then
    echo "Please provide the ACCESS_GROUP name"
    exit
fi


# Define the Polices for the Access Group to enable administering an account

# ACCOUNT MANAGEMENT POLICIES

# All account management services - 38
# Grant access to create and view resource groups
# Also grants access to IAM functions for managing users and access groups
# (This policy alone gives an account admin ~50% of the permissions of an account owner.)
ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Administrator --account-management

# User Management service - 79
# Grant access to invite and view users
# Redundant with --account-management
ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Editor,Operator,Viewer --service-name user-management

# IAM Access Groups Service service - 79
# Grant access to create and view access groups
# Redundant with --account-management
ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Editor,Operator,Viewer --service-name iam-groups


# IAM SERVICES POLICIES
# Similar to env admin policies, but for all resource groups
# Enables acct admin access to all resources in all regions and all resource groups

# "Managing user access with Identity and Access Management"
# https://cloud.ibm.com/docs/Registry?topic=registry-iam
# Container Registry service in All regions - 64
# Manager role grants access to create namespaces for the environment in the image registry
# Administrator role is needed to create clusters
ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Administrator,Manager --service-name container-registry

# "Prepare to create clusters at the account level"
# https://cloud.ibm.com/docs/containers?topic=containers-clusters#cluster_prepare
# Kubernetes Service service in All regions - 45
# Administrator role grants access to create and delete clusters, plus more
# Manager role grants access to manage clusters
# To create clusters, the user will also need Administrator access to the image registry
ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Administrator,Manager --service-name containers-kubernetes

# https://cloud.ibm.com/docs/iam?topic=iam-userroles
# All resources in account (including future IAM enabled services) in All regions - 40
# Administrator role grants access to create and delete service instances (any IAM service), plus more
# Manager role grants access to manage service instances
ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Administrator,Manager

# https://cloud.ibm.com/docs/iam?topic=iam-userroles
# Resource Group - 10
# Viewer roles grants access to view the resource group itself, so the resource group can be specified when creating a service
#ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Viewer --resource-group-name ${RESOURCE_GROUP} --attributes "resourceType=resource-group,resource=${RESOURCE_GROUP}"
#ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Viewer --resource-type "resource-group" --resource ${RESOURCE_GROUP_ID}


echo "Completed creating polices!"