#!/bin/bash
# --------------------------------------------------------------------------------------------------------
# Name : User Access Group Policies
#
# Description: Set the policies in an Access Group to allow user access to resources in
# a Resource Group. Allow full access for using Kubernetes and OpenShift, but limited access
# to existing services, and block creation of new services. Ideal for a system administrator
# to grant access to a team of users.
#
# Author    : Matthew Perrins
# eMail     : mjperrin@us.ibm.com
# Date      : 12th January 2020
#
# --------------------------------------------------------------------------------------------------------
#
# input validation
if [ -z "$1" ]; then
    echo "Usage: acp-users <ACCESS_GROUP> <RESOURCE_GROUP> <REGION> <PREFIX>"
    echo "Create the user Access Policies for an Access Group associated with a Resource Group"
    exit
fi

ACCESS_GROUP=$1
RESOURCE_GROUP=$2
REGION=$3
PREFIX=$4

# input validation
if [ -z "${ACCESS_GROUP}" ]; then
    echo "Please provide the ACCESS_GROUP name"
    exit
fi

# input validation
if [ -z "${RESOURCE_GROUP}" ]; then
    echo "Please provide the RESOURCE_GROUP name"
    exit
fi

# input validation
if [ -z "${REGION}" ]; then
    echo "Please provide the REGION"
    exit
fi

# input validation
if [ -z "${PREFIX}" ]; then
    echo "Please provide the PREFIX label"
    exit
fi


# Define the Polices for the Access Group, this are limited to usage patterns not administration patterns

# Resource Group - 32
ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Viewer,Operator,Reader --resource-group-name ${RESOURCE_GROUP}

# Resource Group - 10
ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Viewer --resource-group-name ${RESOURCE_GROUP} --attributes "resourceType=resource-group,resource=${RESOURCE_GROUP}"

# Kubernetes - 73
ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Viewer,Operator,Editor,Reader,Writer,Manager  --service-name containers-kubernetes

# Kubernetes - 73 with IKS instance
ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Viewer,Operator,Editor,Reader,Writer,Manager --service-name containers-kubernetes --service-instance ${PREFIX}-iks-cluster

# Kubernetes - 73 with OCP instance
ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Viewer,Operator,Editor,Reader,Writer,Manager --service-name containers-kubernetes --service-instance ${PREFIX}-ocp-cluster

# Container Registery - 41
ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Viewer,Operator,Reader --service-name container-registry --region ${REGION}

# Cloudant - 94
ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Editor,Manager --resource-group-name ${RESOURCE_GROUP} --service-name cloudantnosqldb

# COS - 197
ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Viewer,Operator,Editor,Reader,Writer,Manager --resource-group-name ${RESOURCE_GROUP} --service-name cloud-object-storage

# SysDig - 37
ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Writer,Reader,Viewer,Operator --resource-group-name ${RESOURCE_GROUP} --service-name sysdig-monitor

# LogDNA - 69
ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles "Standard Member,Manager,Reader,Editor,Operator,Viewer" --resource-group-name ${RESOURCE_GROUP} --service-name logdna

# AppID - 257
ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Viewer,Operator,Editor,Reader,Writer,Manager --resource-group-name ${RESOURCE_GROUP} --service-name appid


echo "Completed creating polices!"