#!/bin/bash
# --------------------------------------------------------------------------------------------------------
# Name : Environment Administrator Access Group Policies
#
# Description: Set the policies in an Access Group to allow installation and administration
# of the Developer Tools environment into a new or existing OpenShift or Kubernetes cluster.
#
# --------------------------------------------------------------------------------------------------------
#
# input validation
if [ -z "$1" ]; then
    echo "Usage: acp-admin <ACCESS_GROUP> <RESOURCE_GROUP>"
    echo "Create the administration Access Policies for an Access Group associated with a Resource Group"
    exit
fi

ACCESS_GROUP=$1
RESOURCE_GROUP=$2

# input validation
if [ -z "${ACCESS_GROUP}" ]; then
    echo "Please provide the ACCESS_GROUP name"
    exit
fi

# input validation
if [ -z "${RESOURCE_GROUP}" ]; then
    echo "Please provide the RESOURCE_GROUP name"
    exit
fi


RESOURCE_GROUP_ID=$(ibmcloud resource group ${RESOURCE_GROUP} | grep -E "^ID" | sed -E "s/ID: *(.*)/\1/g")
echo "ID for resource group" ${RESOURCE_GROUP} "is" ${RESOURCE_GROUP_ID}

# Define the Polices for the Access Group to enable installation and administration

# "Managing user access with Identity and Access Management"
# https://cloud.ibm.com/docs/Registry?topic=registry-iam
# Container Registry service in All regions - 64
# Manager role grants access to create namespaces for the environment in the image registry
# Administrator role is needed to create clusters
ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Administrator,Manager --service-name container-registry

# "Prepare to create clusters at the account level"
# https://cloud.ibm.com/docs/containers?topic=containers-clusters#cluster_prepare
# Kubernetes Service service in All regions in Resource Group - 34
# Editor role grants access to create and delete clusters in the resource group
# Manager role grants access to manage clusters in the resource group
# To create clusters, the user will also need Administrator access to the image registry
ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Editor,Manager --resource-group-name ${RESOURCE_GROUP} --service-name containers-kubernetes

# "IAM access"
# https://cloud.ibm.com/docs/iam?topic=iam-userroles
# All IAM Services in All regions in Resource Group - 31
# Editor role grants access to create and delete service instances (any IAM service)
# Manager role grants access to manage service instances in the resource group
ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Editor,Manager --resource-group-name ${RESOURCE_GROUP}

# "IAM access"
# https://cloud.ibm.com/docs/iam?topic=iam-userroles
# Resource Group - 10
# Viewer roles grants access to view the resource group itself, so the resource group can be specified when creating a service
#ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Viewer --resource-group-name ${RESOURCE_GROUP} --attributes "resourceType=resource-group,resource=${RESOURCE_GROUP}"
ibmcloud iam access-group-policy-create ${ACCESS_GROUP} --roles Viewer --resource-type "resource-group" --resource ${RESOURCE_GROUP_ID}


echo "Completed creating polices!"