{{- if eq .Values.database.type "sqlite" | not }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "pact-broker.database-secret" . }}
type: Opaque
stringData:
    adapter: {{ .Values.database.type | quote }}
    username: {{ .Values.database.username | quote }}
    password: {{ .Values.database.password | quote }}
    host: {{ .Values.database.host | quote }}
    port: {{ .Values.database.port | quote }}
    name: {{ .Values.database.name | quote }}
{{- end -}}
