apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-toolkit
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-toolkit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: ibm-toolkit
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ibm-toolkit
  namespace: default
data:
  TF_VAR_tools_namespace: tools
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ibm-toolkit
  namespace: default
spec:
  template:
    metadata:
      labels:
        run: ibm-toolkit
    spec:
      serviceAccount: ibm-toolkit
      volumes:
      - name: source
        emptyDir: {}
      containers:
      - image: docker.io/ibmgaragecloud/cli-tools:0.8.0-lite
        name: toolkit
        envFrom:
        - configMapRef:
            name: ibm-toolkit
        volumeMounts:
        - mountPath: /source
          name: source
        command:
        - /bin/bash
        - -c
        - |
          export TF_VAR_login_token=$(oc whoami -t)
          export TF_VAR_server_url=$(oc whoami --show-server)
          git clone -b master --depth=1 https://github.com/ibm-garage-cloud/ibm-garage-iteration-zero.git /source
          cd /source
          ./terraform/runTerraform.sh --ocp -a
      restartPolicy: Never