apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: catalyst-spring-boot-test-task
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: gradle-image
        type: string
        default: gradle:jdk11
  steps:
    - name: build
      image: ${inputs.params.gradle-image}
      workingdir: ${inputs.resources.source.path}
      command:
        - /bin/bash
      args:
        - -c
        - |
          set -x
          ./gradlew assemble --no-daemon
    - name: test
      image: ${inputs.params.gradle-image}
      workingdir: ${inputs.resources.source.path}
      command:
        - /bin/bash
      args:
        - -c
        - |
          set -x
          ./gradlew testClasses --no-daemon
    - name: sonar-scan
      image: ${inputs.params.gradle-image}
      workingdir: ${inputs.resources.source.path}
      command:
        - /bin/bash
      args:
        - -c
        - |
          if [[ -z "${SONARQUBE_URL}" ]]; then
            echo "Skipping Sonar Qube step as Sonar Qube not installed or configured"
            exit 0
          fi
          set -x
          ./gradlew -Dsonar.login=${SONARQUBE_USER} -Dsonar.password=${SONARQUBE_PASSWORD} -Dsonar.host.url=${SONARQUBE_URL} sonarqube
